services:
  backend:
    build: .
    container_name: myshop_backend
    ports:
      - "4000:4000" # Change left port if you want expose different port to host
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # Map node_modules to avoid overwriting from host during dev
    restart: unless-stopped
    command: npm run dev

  db:
    image: postgres:15-alpine
    container_name: myshop_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=myshop
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/migrations/01_init_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./database/seeds/01_dummy_data.sql:/docker-entrypoint-initdb.d/02_seed.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d myshop"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: myshop_pgadmin
    profiles: ["tools"]
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  pgdata:
