<Project Sdk="Uno.Sdk">
    <PropertyGroup>
        <TargetFrameworks>net10.0-desktop</TargetFrameworks>

        <OutputType>Exe</OutputType>
        <UnoSingleProject>true</UnoSingleProject>
        <RootNamespace>CSC13001_my_shop_project</RootNamespace>

        <!-- Display name -->
        <ApplicationTitle>CSC13001-my-shop-project</ApplicationTitle>
        <!-- App Identifier -->
        <ApplicationId>com.companyname.csc13001-my-shop-project</ApplicationId>
        <!-- Versions -->
        <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
        <ApplicationVersion>1</ApplicationVersion>
        <!-- Package Publisher -->
        <ApplicationPublisher>CSC13001-my-shop-project</ApplicationPublisher>
        <!-- Package Description -->
        <Description>CSC13001-my-shop-project powered by Uno Platform.</Description>

        <!--
      UnoFeatures are used to quickly add and manage features enabled for your app.
      https://aka.platform.uno/singleproject-features
    -->
        <UnoFeatures>
          Material;
          Dsp;
          Hosting;
          Toolkit;
          Logging;
          Mvvm;
          Configuration;
          HttpKiota;
          Serialization;
          Localization;
          Navigation;
          ThemeService;
          SkiaRenderer;
        </UnoFeatures>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="LiveChartsCore.SkiaSharpView.Uno.WinUI" />
        <PackageReference Include="Uno.Fonts.Fluent" />
        <PackageReference Include="Uno.Toolkit.Skia.WinUI" />
    </ItemGroup>
</Project>
